---
title: "Section 5"
format: html
---

## Using metrics responsibly in your own applications or evaluations

In this section you will explore: 

-   What you can do if you've been asked to review metrics as part of an assessment process
-   What you can do if you've been asked to include metrics in an application
-   How to get metrics if you need them
-   Limitation of metrics
-   Guidance on how to use metrics

### What do I do if I've been asked to review metrics as part of an application?

If you are asked to judge or review metrics as part of a peer review process for a funder, or as part of a recruitment or promotion process for another university, you can use the text below as a response rather than participating in that aspect of the assessment.

“The University of Edinburgh supports responsible research assessment and is a signatory of DORA and CoARA, therefore I am not able to comment on this aspect of the application”

### What do I do if I've been asked to include metrics in an application?

Metrics can provide a quantitative snapshot of aspects of a research output, or a group of research outputs.  

The production of a research output is a core part of the research lifecycle. However, it's only one part of that lifecycle, and of your broader role as a researcher and academic. Your knowledge of, and your contribution to, your research area is more comprehensive, complex and nuanced than a simple number or list of outputs.  

If you haven’t been asked to provide metrics as part of an application process we suggest you don't provide them. Metrics don't supersede your expert opinion and knowledge of your research contribution. Instead, a narrative approach may be better able to give the full breadth of your contribution to the research, and your contribution as a researcher. The only time you have to use metrics is if the assessment process asks you to provide them, and you can always ask if this is necessary and offer another route to providing the same information.

### **How to get metrics if you need them** 

You can obtain metrics by using an indexing database such as:

-   [Scopus](https://www.scopus.com/){target="_blank"}. ^+^ 
-   [Web of Science](https://webofknowledge.com/WOS){target="_blank"}. ^+^
-   [Dimensions](https://app.dimensions.ai/discover/publication){target="_blank"}.\*
-   [Google Scholar](http://scholar.google.co.uk/citations?view_op=top_venues&hl=en){target="_blank"}.\*
-   [Open Alex](https://openalex.org/){target="_blank"}.\*

Some of these databases are free to use with an account(\*) and some of these are accessible via University of Edinburgh subscriptions(^+^). They all have a search function which will allow you to search for your name and/or Researcher ID such as [ORCID](https://support.orcid.org/hc/en-us){target="_blank"} and from there you can review how your research has been indexed by these systems. 

Using more than one source of metrics is a good practice as systems index at different rates and from different sources. 

### **Limitations of metrics**

-   Not all research outputs will be indexed, and therefore might not be included in the calculation of a research metric
    -   Typically journal articles are indexed, and some books may be indexed, smaller publishers may not index their journals
    -   STEM journals are more likely to be indexed than Arts, Humanities and Social Sciences journals
    -   It can take up to six months from publication for articles to be indexed
    -   Content may have been wrongly affiliated to a researcher or their content wrongly associated with someone else
-   Citations take a long time to accrue, this favours older papers over new papers, and those that have been publishing longer over those earlier in their career
-   There is no way of knowing if citations are positive or negative from metrics. Note, some services do perform sentiment analysis on citations.

### **Using metrics as supporting evidence** 

If you use metrics you need to use them responsibly.  There are many different metrics, for many different purposes, from many different sources.  You should use the most appropriate metric according to your needs. Below you'll find examples (both poor and better) of how metrics could be used to support statements about your research.  If you aren't asked to provide metrics in an application we suggest you don't provide them, include a narrative statement to explain the significance and reach of your work.

### **Examples** 

**Example of poor use** 

*I publish in top journals* 

Why this is bad? There's no context and it's a vague statement. It is equating the quality of your individual research output with the overall quality of the whole journal's catalogue. 

**Example of better use** 

*\[citation of paper\] is my most highly cited paper which according to \[source such as Scopus or Google Scholar\] has been cited 150 times. It has been cited by \[policy document\]*  

Why this is better? The statement is specific. There is a source identified and there is a metric that is verifiable. You’ve provided a link to a publication that demonstrates some of the impact the research has had.  

The statement could be made even better by stating the date you checked the number of citations, as metrics accumulate over time. You could use a normalised metric (e.g. field weighted citation impact) which is gives a fairer assessment rather than a count. You could also talk about the impact of your research more. 

**Example of best use**  

*\[citation of paper\] is my top performing paper according to Scopus on \[date you checked\] it has been cited 150 times and has a field-weighted citation index of 4.3 (1 being average). It has been cited by \[policy document\]. Following its publication I was invited to join a government working group to explore improving government policy in this area.*  

Why this is good? You’ve given a source and date for your metrics, you've used multiple metrices and you’ve used a normalised metric which makes for a fairer comparison. You’ve explained that your output has led to impact. 

### **How to identify your 'best' publications** 

It's not uncommon for applicants to be asked to highlight their 'best' research publications. How you quantify 'best' will depend on the context of what you are applying for, your discipline, and what the assessor has asked for.  A more useful way to consider this questions could be to identify your "most significant" research output.

It can be useful to identify 3-5 research outputs and annotate them in your publication list emphasising your contribution to the research, the development of the output, and any academic or broader impact the research has had.

**Example of an annotation on a publication list**

Author A.N, Writer B.P, Researcher V.I, Scientist L.P. Treatment of Latent Infection: A Network Meta-Analysis. Annals of Medicine (2019) 424(8):419-28 

*"I intellectually conceived and conducted this work, extracted and reviewed the data, and wrote the majority of the paper. I attended an international government expert panel to present this work, which led to its use as the scientific foundation for their global ‘Guidelines on the management of infection’, 2019 (which I contributed to the writing of) and an associated publication."*

Thank you for taking the time to complete this course.  If you would like to test your knowledge, [complete this quiz](https://forms.office.com/e/z6Tn2WzhC1){target="_blank"}.

